### ISSUE TITLE
bughuntoor - Adversary can DoS all users from regular withdraws

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#30]
bughuntoor

high

# Adversary can DoS all users from regular withdraws

## Summary
Adversary can DoS all users from regular withdraws

## Vulnerability Detail
In `JOJODealer`, whenever users would like to withdraw, they'd have to first request a withdraw and then after `withdrawTimelock` passes, they can call `executeWithdraw`. 
```solidity
    function requestWithdraw(
        Types.State storage state,
        address from,
        uint256 primaryAmount,
        uint256 secondaryAmount
    )
        external
    {
        require(isWithdrawValid(state, msg.sender, from, primaryAmount, secondaryAmount), Errors.WITHDRAW_INVALID);
        state.pendingPrimaryWithdraw[msg.sender] = primaryAmount;
        state.pendingSecondaryWithdraw[msg.sender] = secondaryAmount;
        state.withdrawExecutionTimestamp[msg.sender] = block.timestamp + state.withdrawTimeLock;
        emit RequestWithdraw(msg.sender, primaryAmount, secondaryAmount, state.withdrawExecutionTimestamp[msg.sender]);
    }
```
In order for a withdraw request to succeed, it needs to pass the `isWithdrawValid`
```solidity
    function isWithdrawValid(
        Types.State storage state,
        address spender,
        address from,
        uint256 primaryAmount,
        uint256 secondaryAmount
    )
        internal
        view
        returns (bool)
    {
        return spender == from
            || (
                state.primaryCreditAllowed[from][spender] >= primaryAmount
                    && state.secondaryCreditAllowed[from][spender] >= secondaryAmount
            );
    }
```

The problem here is that the request allows for both `primaryAmount` and `secondaryAmount` to be exactly 0. Any user can call `requestWithdraw` for another user with both values being 0 and the check above would pass, effectively overwriting any current request. 

A malicious user could back-run any withdraw request with such 0 values and overwrite it, basically cancelling it.

## Impact
Adversary can fully DoS regular withdraws. 

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/libraries/Funding.sol#L51C1-L67C6

## Tool used

Manual Review

## Recommendation
Upon requesting a withdraw, check that at least one of the values is non-zero. 

Duplicate of #53

**Comment by nevillehuang** [comment]
This and #75 is actually describing something similar to #53, but this is actually not possible due to a mistake in #53 not allowing `pendingPrimaryWithdraw` and `pendingSecondaryWithdraw` and `withdrawExecutionTimestamp` to be overwritten.

So by the current logic, the `msg.sender` and `from` must match to sucessfully execute a withdrawal i.e. user can only withdraw on his own. Additionally, front-running/back-running is not an issue on arbitrum given the mempool is private.

Care should be taken to fix #53, if not this issue can actually arise, but by current code logic, this is not possible.

**Comment by deadrosesxyz** [comment]
Escalate
The fact there is other mistake in the code does not make this issue invalid. Furthermore, it does not require scanning the mempool as a user can just make a call after the victim’s innocent request executes (as they need to wait time)

The usage of msg.sender is a different mistake which is not expected behaviour.

**Comment by sherlock-admin** [comment]
> Escalate
> The fact there is other mistake in the code does not make this issue invalid. Furthermore, it does not require scanning the mempool as a user can just make a call after the victim’s innocent request executes (as they need to wait time)
> 
> The usage of msg.sender is a different mistake which is not expected behaviour. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@deadrosesxyz can you provide a poc at the point of the contest code logic that shows this is possible? 

Because as far as I know, requestWithdraw is broken and nobody can withdraw in place of another user, so it makes this issue not possible. But I think the sponsor should still take a look @JoscelynFarr

**Comment by deadrosesxyz** [comment]
Contest code has a mistake which prevents this from happening. Invalidating the issue based on another issue would be the same as invalidating all issues since the project’s code will be broken as it uses solidity version not supported by Arbitrum. (hence no issue described could actually occur)

Another equivalent would be to invalidate ‘drain all funds’ issue in a codebase where ‘deposit’ function does not work. One issue does not invalidate the other.

It would make sense to invalidate the issue if msg.sender was used on purpose. It clearly wasn’t

**Comment by nevillehuang** [comment]
@deadrosesxyz I agree with you, but based on recent history of invalidation results [such as this one](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/207#issuecomment-1870333945) and [this one](https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance-judging/issues/51#issue-comment-box) I think this is going to be invalid, because there is no proof at time of contest this bug can actually occur, so if jojo deploys the contracts, no impact from this issue will happen (Same can be said about your above mentioned scenario)

Also I believe this falls under this specific rule, especially the second half

> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

**Comment by deadrosesxyz** [comment]
Final message as not to create unnecessary spam

1. If this is invalidated based on the other issue, all issues except the Solidity version one should be invalidated (which I believe is wrong)
2. As per Sherlock rules
> Historical decisions are not considered sources of truth.

I sincerely believe this to be a valid issue. Would love to hear sponsor/ @Czar102 thoughts

**Comment by nevillehuang** [comment]
@deadrosesxyz Can you elaborate more on point 1? I believe that statement is wrong since all other issues are not dependent on any other issues similar to this one.

**Comment by deadrosesxyz** [comment]
Due to arb pragma issue, upon deployment code will be unusable, hence no other issue could be replicated (as users will be unable to operate with the contract at all)

**Comment by nevillehuang** [comment]
@deadrosesxyz Fair point, I will let escalation play out given it is still ongoing debate whether that issue is valid or not, and let @Czar102 take it from here.

**Comment by JoscelynFarr** [comment]
Hi, we will have an internal discussion and give the result back.

**Comment by vshtanko** [comment]
My issue is the same https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/75 but is not marked as duplicate

**Comment by nevillehuang** [comment]
@vshtanko It is marked as a duplicate, please double-check.

Also @deadrosesxyz the arb issue is likely to be invalid, so not sure how it will affect judgement of this, but I believe no further discussions is required as of now until @Czar102 makes a decision.

**Comment by JoscelynFarr** [comment]
After internal discussion, we decided to add a check that at least one of the values is non-zero
Fixed PR: https://github.com/JOJOexchange/smart-contract-EVM/commit/d8f86015c6681796d37c1dd148e6f2ce97c5c151

**Comment by IAm0x52** [comment]
Fix looks good. Now requires a non-zero allowance amount.

**Comment by vshtanko** [comment]
So sponsor decides to fix this, but it is somehow not a valid issue?

**Comment by Evert0x** [comment]
Will revisit this issue later, but I believe it's a Medium as the functionality of the protocol can be seriously affected.

**Comment by nevillehuang** [comment]
@Evert0x Consider this comment before making a decision https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/30#issuecomment-1913114684. I believe this will introduce inconsistencies for judging if you accept this finding when this issue cannot occur during the time of contest.

**Comment by deadrosesxyz** [comment]
@Evert0x this would allow DOS for all user withdrawals, shouldn't this be considered a high?

**Comment by nevillehuang** [comment]
@deadrosesxyz Again this DoS cannot occur during the time of contest, so I believe even if this issue is valid, it should be a duplicate of #53, because it is only possible after the fix has been implemented for that issue

But you can see clearly from sherlocks future fix rules this is not valid. This would require a rule change to validate this issue.

**Comment by deadrosesxyz** [comment]
i'll leave it to Evert, but here are some of my thoughts: 

the rule makes sense in 99% of the cases, but there should be some exceptions. E.g. if the contract's deposit function was not usable and there was no way to get funds in the contract in the first place, should then all vulnerabilities found which include contract draining be marked as invalid? 

also, given this rule, if I didn't escalate this issue, it would remain unfixed and get to production. Invalidating this issue would be a mistake.

**Comment by nevillehuang** [comment]
I believe the most fair outcome is to validate this issue and remove consideration from judging results, and then consider a rule change to cater to such exceptions for future issues.

However, I believe this issue should have been brought up as a potential issue arising to the fix of #53 (I believe you missed that issue). So it is fair to say you did not consider the possibility of this issue occuring by proving it with a PoC (in which you would have discovered issue #53).

**Comment by IllIllI000** [comment]
`Future issues: Issues that result out of ... a future change in the code (as a fix to another issue) are not valid issues.` I'm pretty sure it means bugs _caused_ by future changes are invalid, not that _existing_ bugs, prevented by other bugs, are invalid.

**Comment by nevillehuang** [comment]
@IllIllI000 a future change can only arise from an existing bug, thats my understanding. If theres no existing bug, there is no need for a future change. In this context, there is an upcoming change for a issue #53 for this issue to occur.

Am i missing something?

**Comment by IllIllI000** [comment]
An upgrade, which stomps over a storage slot because there was no __gap, would be a future change that is not necessitated by the fix for an existing bug. The code works just fine until someone makes the change.

**Comment by nevillehuang** [comment]
@IllIllI000 How would you even know the logic to an upgrade during the time of a contest to determine the appropriateness of the rule? I think lets stop the discussion until @Evert0x clarify the correct purpose and understanding of the rule

I believe if you are correct, the issues I mentioned before as examples are wrongly considered and am puzzled why head of judging did not correct me then.

Another thing I want to add is, if #53 is not fixed, the whole request withdrawal mechanism would function as per normal with no withdrawal dos impact. Actually I would be interested to hear from @JoscelynFarr why requesting withdrawals on behalf of others is allowed, given no core functionality is actually broken, users can request withdrawal by themselves, so that issue could possibly be low severity. Possibly an external integration?

**Comment by JoscelynFarr** [comment]
> @IllIllI000 How would you even know the logic of an upgrade during the time of a contest to determine the appropriateness of the rule? I think lets stop the discussion until @Evert0x clarify the correct purpose and understanding of the rule
> 
> I believe if you are correct, the issues I mentioned before as examples are wrongly considered and am puzzled why head of judging did not correct me then.
> 
> Another thing I want to add is, if #53 is not fixed, the whole request withdrawal mechanism would function as per normal with no withdrawal dos impact. Actually I would be interested to hear from @JoscelynFarr why requesting withdrawals on behalf of others is allowed, given no core functionality is actually broken, users can request withdrawal by themselves, so that issue could possibly be low severity. Possibly an external integration?

If the `fastWithdrawDisabled` flag is set to true, regular users won't be able to use the fast withdraw feature. However, if they are approved by our internal admin who is on the `fastWithdrawalWhitelist`, they can still use the fast withdraw feature with the help of our admin.

**Comment by Czar102** [comment]
Given that #53 is a valid issue, this finding's author didn't have to find all other issues to notice whether this one is feasible. Hence, this issue presents a valid concern. It resulted of a misunderstanding of the code, but this misunderstanding was caused by a wrong implementation, and it't not submitter's fault that other parts of the system didn't work as intended.

Both #53 and this issue are about the wrong mapping (key(s)) used, which may lead to different impacts. I think it's reasonable to consider them duplicates.

**Comment by deadrosesxyz** [comment]
> Both https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/53 and this issue are about the wrong mapping (key(s)) used, which may lead to different impacts. I think it's reasonable to consider them duplicates.

@Czar102 I honestly don't quite get your point here. This issue nowhere includes wrong mapping/ key(s) used. The issue stems from the fact any user can create a 0-value withdraw request, which overwrites the current withdraw request.

This is an access control issue and is not about a wrong mapping used. Perhaps you could point to me where you believe a wrong mapping is used within this issue?

**Comment by nevillehuang** [comment]
@Czar102 I agree with you, can be duplicates, but this is abit of a unique scenario. Can you clarify how to approach this type of issues going forward, given where a fix towards an issue will result in the possibility of another?

**Comment by Czar102** [comment]
First, some context on my point of view.

I think the core issue here is that a withdrawal can be made either per operator, and an operator can't withdraw for multiple users or at all (#53), or per user, and operators can overwrite withdrawals (#30). A single fix would be to make the mapping 2-dimensional (user and operator being the keys) and allowing the user execute the withdrawal.

#30 assumes that #53 will be fixed without making adequate modifications in other parts of code (since `msg.sender` is used in the code being audited, there is no issue of someone else overwriting that value).

So, I believe that both these issues are locating the same issue, but from very different perspectives. This submission misses some errors in the workings of the codebase, nevertheless it spots an error in the intended logic of the contract.

In case the vulnerabilities are entirely unrelated, I believe it is fair to validate both of them. But assuming an incorrect fix to any other issue (as stated in the rules) invalidates the submission. If an issue assumes the system works as intended while it doesn't and the reason of the system not working as intended gives direct grounds for the issue being non-exploitable (I'll work on the exact language here) allows these issues to be considered duplicates.

**Comment by Czar102** [comment]
Result:
Medium
Duplicate of #53

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [deadrosesxyz](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/30/#issuecomment-1913112660): accepted
