### ISSUE TITLE
giraffe - Gas griefing of Owner through requestWithdraw

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#88]
giraffe

medium

# Gas griefing of Owner through requestWithdraw

## Summary
In FundingRateArbitrage.sol, an attacker can spam withdraw requests with an amount that could make the next step (permitWithdrawRequests) fail, causing DOS and gas grief to the Owner.

## Vulnerability Detail
On FundingRateArbitrage.sol, withdrawal is a two-step process: user submits `requestWithdraw` and owner batches requests through `permitWithdrawRequests`. 

An attacker could cause gas griefing to the owner by spam submission of `requestWithdraw` with the minimum value required to clear the check for `withdrawEarnUSDCAmount.decimalMul(index) >= withdrawSettleFee`.

After a time gap, owner will attempt to permit the withdraw requests. However, at this point it is likely that `index` would have drifted from the original value at time of request. If `index` is less than the value before, this check in `permitWithdrawRequests` will fail:
```solidity
uint256 USDCAmount = request.earnUSDCAmount.decimalMul(index);

require(USDCAmount >= withdrawSettleFee, "USDCAmount need to bigger than withdrawSettleFee");
```

This would result in wasted gas and possible DOS of other users' withdrawal requests as the Owner makes multiple attempts to call `permitWithdrawRequest` but fails if any of the requests doesn't pass the above check.
## Impact
Cost of attack:
Referencing FundingRateArbitrageTest.t.sol, the team sets `withdrawSettleFee = 2e6`. So for the cost of 2 usd per `requestWithdraw` an attacker can reasonably spam hundreds or thousands of requests - each with a likelihood of failing at the next permit step. 

Cost to owner:
On Arbitrum a L2, the majority of gas costs are attributed to calldata. When the owner calls `permitWithdrawRequests(uint256[] memory requestIDList)` the Owner has to pay for each request ID of 32 bytes length. For each zero byte = 4 gas, non-zero byte = 16 gas. So assuming 2 non-zero bytes and 30 zero bytes per request = 152 gas per requestId. If an attacker submits 1000 requests, that equals 152,000 gas * 25 gwei (L1 gas cost) = ~$10 per tx. 

As the requestIds are submitted in batches, other users with valid withdrawals will fail and be DOS-ed as well. 
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L294
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L310
## Tool used
Manual Review

## Recommendation
Set withdrawal threshold based on `repayJUSDAmount` instead of fees. Consider adding a buffer to allow for fluctuations in `index`. Lastly, also consider allowing Owner to delete/remove requests from the `withdrawRequests` array.

**Comment by nevillehuang** [comment]
Invalid, see similar finding [here](https://github.com/sherlock-audit/2023-12-symm-io-judging/issues/48#issuecomment-1881363552). Admin can permit specific withdraw request and won't be griefed as seen [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L307C49-L307C67)

**Comment by giraffe0x** [comment]
Escalate.

This is clearly different from [here](https://github.com/sherlock-audit/2023-12-symm-io-judging/issues/48#issuecomment-1881363552) which did not recognize that there is a check for `withdrawEarnUSDCAmount.decimalMul(index) >= withdrawSettleFee` in `requestWithdraw()` so it's incorrect that an attacker can spam 1 wei requests which would fail this check. That issue also fails to realize that owner can decide how many input `requestIds`, so it is unlikely that `permitWithdrawRequests` will run out of gas if owner knows what he is doing.

My issue recognizes the two points above. However, DOS is still possible because owner may not know which requestIds will fail. It is not clear how owner will automate the calling of `permitWithdrawRequests()`, but lets assume it is run by a script that clears the queue of requestIds 5 at a time:

As described above, if an attacker spam submits multiple withdraw requests at exactly `withdrawEarnUSDCAmount.decimalMul(index) = withdrawSettleFee` then there is a chance that a slight drop in `index` will result in `permitWithdrawRequests` failing. Furthermore, if the user becomes blacklisted by USDC, then `permitWithdrawRequest` will also fail. To note that if any one of the requestIds fail, the entire batch fails. 

So, if there are actual users who submit valid withdraw requests which are batched together with these spam requests, then their requests will be DOS and delayed. Plus with each failed permit, owner also wastes gas. 

I had previously discussed this issue in a private thread with sponsor who agreed this could be an issue for them to look into. Suggest to re-look and reconsider this to be valid. Thank you.

**Comment by sherlock-admin** [comment]
> Escalate.
> 
> This is clearly different from [here](https://github.com/sherlock-audit/2023-12-symm-io-judging/issues/48#issuecomment-1881363552) which did not recognize that there is a check for `withdrawEarnUSDCAmount.decimalMul(index) >= withdrawSettleFee` in `requestWithdraw()` so it's incorrect that an attacker can spam 1 wei requests which would fail this check. That issue also fails to realize that owner can decide how many input `requestIds`, so it is unlikely that `permitWithdrawRequests` will run out of gas if owner knows what he is doing.
> 
> My issue recognizes the two points above. However, DOS is still possible because owner may not know which requestIds will fail. It is not clear how owner will automate the calling of `permitWithdrawRequests()`, but lets assume it is run by a script that clears the queue of requestIds 5 at a time:
> 
> As described above, if an attacker spam submits multiple withdraw requests at exactly `withdrawEarnUSDCAmount.decimalMul(index) = withdrawSettleFee` then there is a chance that a slight drop in `index` will result in `permitWithdrawRequests` failing. Furthermore, if the user becomes blacklisted by USDC, then `permitWithdrawRequest` will also fail. To note that if any one of the requestIds fail, the entire batch fails. 
> 
> So, if there are actual users who submit valid withdraw requests which are batched together with these spam requests, then their requests will be DOS and delayed. Plus with each failed permit, owner also wastes gas. 
> 
> I had previously discussed this issue in a private thread with sponsor who agreed this could be an issue for them to look into. Suggest to re-look and reconsider this to be valid. Thank you. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
After internal discussion, we plan to add a minimum request amount to prevent DOS

**Comment by nevillehuang** [comment]
@giraffe0x @JoscelynFarr , I believe while it could be nice to fix this on chain, I believe this is low severity/invalid,

- You are speculating on off-chain mechanisms of how the correct requestIds are indexed, which in itself is out of scope. It is trusted that admin will index the appropriate requestIds accordingly based on this [event emitted](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L298)
- Blacklisted users are not considered as valid issues based on sherlocks black list rule of harming users themselves
- If there is a drop in index price, it is expected behavior that permitting such withdrawals would fail. This is akin to the root cause highlighted in #35, where in I believe user should respect the risk taken for depositing and the latest index price, so they should re-request a withdrawal for subsequent re-permit. Like mentioned, the loss is on paper, given the index price can always recover, so the user can still retain their JUSD initially obtained relative to their collateral value deposited.

**Comment by JoscelynFarr** [comment]
It is permitted for the index withdrawal off-chain, however, it would be better to include a minimum function. I am unsure about how to assess the severity of the issue. Perhaps we can leave this to the admin of Sherlock.

**Comment by giraffe0x** [comment]
@nevillehuang, I think your 2nd and 3rd point misses my argument. An attacker could choose to waste funds (by submitting many cheap withdraw requests, or by getting blacklisted) to DOS other honest users' withdrawals or to waste owner's gas.

Because `permitWithdrawRequests()` is meant to execute withdraw requests in batches, the function call will fail if the batch includes withdraw requests from the attacker. Owner could choose to filter out these requests, but because of the low cost of attack + the possibility that index could change slightly at time of transaction -- it is probable that dishonest requests could be batched and cause revert.

Since sponsor has considered this finding vaulable and will fix, it should be a valid medium issue.

**Comment by nevillehuang** [comment]
@giraffe0x Sponsors opinion can be useful in supporting your argument, but it will never be considered during the validity of an issue. 

When you say perform in batches, again you are assuming off-chain mechanisms that admin would make a mistake and batch malicious transactions without verification, which in itself is admin error. And even when so, they can simply permit again after the revert by batching the correct requestIds. Additional requestIds will not impact the already indexed requestIds. I believe this should remain as invalid.

**Comment by Czar102** [comment]
I agree with the Lead Judge. It is owner's responsibility to check that the transaction isn't reverting. Even if a tx fails, the owner can always resubmit the operation. Please note that this can be done for withdrawals one by one. This is a low severity issue.

Planning to reject the escalation and leave the issue as is.

**Comment by IAm0x52** [comment]
Fixed [here](https://github.com/JOJOexchange/smart-contract-EVM/commit/d783c1100459c4e0e224fb478b144c286c8393ca). 

Adds a minimum withdraw amount.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [giraffe0x](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/88/#issuecomment-1913143235): rejected
